g++ -o sitega_thr_dist_mat sitega_thr_dist_mat.cpp 
g++ -o andy0bsn2 andy0bsn2.cpp
g++ -o andy1_mat andy1_mat.cpp
g++ -o andy02 andy02.cpp
g++ -o monte0dg monte0dg.cpp
chmod a+x andy0bsn2 
chmod a+x andy1_mat
chmod a+x andy02
chmod a+x monte0dg
chmod a+x sitega_thr_dist_mat
chmod a+x bootstrap
chmod a+x scan 
chmod a+x train
