g++ -o sitega_thr_dist_mat.exe sitega_thr_dist_mat.cpp 
g++ -o andy0bsn2.exe andy0bsn2.cpp
g++ -o andy1_mat.exe andy1_mat.cpp
g++ -o andy02.exe andy02.cpp
g++ -o monte0dg.exe monte0dg.cpp
chmod a+x andy0bsn2.exe 
chmod a+x andy1_mat.exe
chmod a+x andy02.exe
chmod a+x monte0dg.exe
chmod a+x sitega_thr_dist_mat.exe
chmod a+x bootstrap
chmod a+x scan 
chmod a+x train
